export const FIRST_NAMES = [
  'Thabo', 'Amara', 'Liam', 'Nomsa', 'Chen', 'Priya', 'Diego', 'Fatima', 'Kwame', 'Sofia',
  'Ivan', 'Grace', 'Mateo', 'Aisha', 'Noah', 'Lerato', 'Rahul', 'Elena', 'Sipho', 'Hana',
  'Marcus', 'Zanele', 'Tom', 'Ngozi', 'Andres', 'Mei', 'Pieter', 'Yara', 'Jack', 'Naledi',
  'Omar', 'Lucia', 'Kofi', 'Anja', 'Wei', 'Tendai', 'Carlos', 'Ruth', 'Dmitri', 'Bongani',
  'Sarah', 'Hassan', 'Lena', 'Bruno', 'Ayanda', 'Felix', 'Mariam', 'Jonas', 'Katya', 'Samuel',
  'Precious', 'Andre', 'Ines', 'Tariq', 'Emma', 'Sizwe', 'Nadia', 'Owen', 'Chiara', 'Musa',
]

export const LAST_NAMES = [
  'Mokoena', 'Nguyen', 'Okafor', 'Silva', 'Petrov', 'Dlamini', 'Hughes', 'Zhang', 'Fernandez', 'Patel',
  'Mensah', 'Kowalski', 'Ncube', 'Rossi', 'Anderson', 'Adeyemi', 'Baptiste', 'Novak', 'Khan', 'Botha',
  'Ferreira', 'Mahlangu', 'Sullivan', 'Ivanov', 'Diallo', 'Wong', 'Camara', 'Reyes', 'Larsen', 'Naidoo',
  'Muller', 'Osei', 'Costa', 'Mwangi', 'Schmidt', 'Radebe', 'Torres', 'Banda', 'Jansen', 'Ali',
  'Sithole', 'Novikov', 'Kaur', 'Marais', 'Owusu', 'Perez', 'Steyn', 'Chirwa', 'Lindqvist', 'Moyo',
]

export const JOB_TITLES: readonly (readonly [string, string, string])[] = [
  // [title, occupation_group, work_location]
  ['Mine Manager', 'management', 'mixed'],
  ['Production Superintendent', 'management', 'mixed'],
  ['Shift Supervisor', 'supervisor', 'underground'],
  ['Pit Supervisor', 'supervisor', 'surface'],
  ['Mining Engineer', 'professional', 'office'],
  ['Geologist', 'professional', 'mixed'],
  ['Mine Surveyor', 'professional', 'mixed'],
  ['Metallurgist', 'professional', 'plant'],
  ['Ventilation Officer', 'professional', 'underground'],
  ['Geotechnical Engineer', 'professional', 'mixed'],
  ['Haul Truck Operator', 'operator', 'surface'],
  ['Excavator Operator', 'operator', 'surface'],
  ['Dozer Operator', 'operator', 'surface'],
  ['Drill Rig Operator', 'operator', 'surface'],
  ['LHD Operator', 'operator', 'underground'],
  ['Continuous Miner Operator', 'operator', 'underground'],
  ['Shotfirer', 'operator', 'underground'],
  ['Roof Bolter', 'operator', 'underground'],
  ['Diesel Mechanic', 'artisan', 'mixed'],
  ['Auto Electrician', 'artisan', 'mixed'],
  ['Boilermaker', 'artisan', 'plant'],
  ['Fitter and Turner', 'artisan', 'plant'],
  ['Electrician', 'artisan', 'plant'],
  ['Plant Operator', 'operator', 'plant'],
  ['Control Room Operator', 'operator', 'plant'],
  ['Laboratory Technician', 'professional', 'plant'],
  ['Safety Officer', 'professional', 'mixed'],
  ['Environmental Officer', 'professional', 'surface'],
  ['Emergency Response Officer', 'professional', 'mixed'],
  ['Occupational Health Nurse', 'professional', 'office'],
  ['Storeman', 'administration', 'surface'],
  ['Buyer', 'administration', 'office'],
  ['Weighbridge Operator', 'administration', 'surface'],
  ['Payroll Officer', 'administration', 'office'],
  ['HR Business Partner', 'professional', 'office'],
  ['Trainer and Assessor', 'professional', 'mixed'],
  ['General Hand', 'labourer', 'surface'],
  ['Cleaner', 'labourer', 'surface'],
  ['Security Officer', 'administration', 'surface'],
  ['Apprentice Mechanic', 'apprentice', 'mixed'],
]

export const SPARE_PARTS: readonly (readonly [string, string, string, number])[] = [
  // [name, category, uom, unit cost]
  ['Hydraulic hose 1in x 2m', 'spare_part', 'ea', 148],
  ['Engine oil filter CAT 793', 'spare_part', 'ea', 92],
  ['Air filter primary 785C', 'spare_part', 'ea', 210],
  ['Fuel filter assembly', 'spare_part', 'ea', 76],
  ['Alternator 24V 150A', 'spare_part', 'ea', 1840],
  ['Starter motor heavy duty', 'spare_part', 'ea', 2260],
  ['Turbocharger cartridge', 'spare_part', 'ea', 7450],
  ['Brake pad set rear', 'spare_part', 'set', 1290],
  ['Suspension strut nitrogen', 'spare_part', 'ea', 5600],
  ['Final drive seal kit', 'spare_part', 'kit', 940],
  ['Bucket tooth adapter', 'spare_part', 'ea', 420],
  ['GET bucket tooth', 'spare_part', 'ea', 265],
  ['Cutting edge 2.4m', 'spare_part', 'ea', 1120],
  ['Track shoe assembly', 'spare_part', 'ea', 780],
  ['Idler roller', 'spare_part', 'ea', 340],
  ['Conveyor belt splice kit', 'spare_part', 'kit', 2100],
  ['Conveyor idler roller 152mm', 'spare_part', 'ea', 118],
  ['Crusher mantle', 'spare_part', 'ea', 18500],
  ['Crusher concave segment', 'spare_part', 'ea', 6400],
  ['Mill liner bolt M36', 'spare_part', 'ea', 34],
  ['Mill rubber liner panel', 'spare_part', 'ea', 2850],
  ['Slurry pump impeller', 'spare_part', 'ea', 4300],
  ['Slurry pump throatbush', 'spare_part', 'ea', 1950],
  ['Mechanical seal 100mm', 'spare_part', 'ea', 1480],
  ['Cyclone apex 75mm', 'spare_part', 'ea', 520],
  ['Screen panel polyurethane', 'spare_part', 'ea', 168],
  ['V-belt SPB 3550', 'spare_part', 'ea', 64],
  ['Gearbox oil 80W-90 208L', 'lubricant', 'drum', 1120],
  ['Hydraulic oil ISO 68 208L', 'lubricant', 'drum', 980],
  ['Engine oil 15W-40 208L', 'lubricant', 'drum', 1040],
  ['Grease EP2 180kg', 'lubricant', 'drum', 760],
  ['Coolant concentrate 20L', 'consumable', 'ea', 185],
  ['Welding electrode 3.2mm', 'consumable', 'kg', 12],
  ['Oxygen cylinder G size', 'consumable', 'ea', 240],
  ['Cutting disc 230mm', 'consumable', 'ea', 8],
  ['Rock bolt 2.4m resin', 'consumable', 'ea', 26],
  ['Wire mesh sheet 3.0x1.2m', 'consumable', 'ea', 74],
  ['Shotcrete accelerator 25kg', 'consumable', 'bag', 96],
  ['Drill bit 102mm button', 'consumable', 'ea', 615],
  ['Drill rod 3.6m T51', 'consumable', 'ea', 890],
  ['Drill shank adapter', 'consumable', 'ea', 720],
  ['ANFO prill 25kg bag', 'explosive', 'bag', 68],
  ['Emulsion explosive bulk', 'explosive', 'kg', 3.4],
  ['Booster 400g cast', 'explosive', 'ea', 22],
  ['Electronic detonator', 'explosive', 'ea', 34],
  ['Detonating cord 10g/m', 'explosive', 'm', 2.1],
  ['Sodium cyanide briquette', 'reagent', 'kg', 4.6],
  ['Quicklime bulk', 'reagent', 't', 245],
  ['Activated carbon 500kg', 'reagent', 'bag', 3400],
  ['Hydrochloric acid 33%', 'reagent', 'l', 1.8],
  ['Flocculant anionic 25kg', 'reagent', 'bag', 320],
  ['Frother MIBC 200L', 'reagent', 'drum', 1650],
  ['Collector SIBX 1t', 'reagent', 't', 3100],
  ['Magnetite dense medium', 'reagent', 't', 285],
  ['Hard hat vented', 'ppe', 'ea', 42],
  ['Safety boots steel toe', 'ppe', 'pair', 138],
  ['Overalls flame retardant', 'ppe', 'ea', 165],
  ['Gloves impact resistant', 'ppe', 'pair', 28],
  ['Safety glasses clear', 'ppe', 'ea', 14],
  ['Earplugs corded box 200', 'ppe', 'box', 96],
  ['P2 respirator box 20', 'ppe', 'box', 148],
  ['Cap lamp rechargeable', 'ppe', 'ea', 385],
  ['Self rescuer 60min', 'ppe', 'ea', 940],
  ['Portable gas detector 4-gas', 'safety', 'ea', 1350],
  ['Fall arrest harness', 'ppe', 'ea', 420],
  ['Fire extinguisher 9kg DCP', 'safety', 'ea', 210],
  ['Spill kit 240L', 'safety', 'ea', 640],
  ['First aid kit workplace', 'safety', 'ea', 185],
  ['Haul truck tyre 40.00R57', 'tyre', 'ea', 42000],
  ['Loader tyre 35/65R33', 'tyre', 'ea', 12400],
  ['Light vehicle tyre LT265', 'tyre', 'ea', 340],
  ['Battery 12V 1000CCA', 'electrical', 'ea', 480],
  ['Cable 3-core 95mm2', 'electrical', 'm', 46],
  ['Contactor 400A', 'electrical', 'ea', 1620],
  ['VSD 250kW', 'electrical', 'ea', 24500],
  ['Limit switch heavy duty', 'electrical', 'ea', 210],
  ['Pressure transmitter 0-40bar', 'electrical', 'ea', 890],
  ['Flow meter DN200 magnetic', 'electrical', 'ea', 5200],
  ['Torque wrench 1500Nm', 'tool', 'ea', 1450],
  ['Impact socket set 3/4in', 'tool', 'set', 620],
]

export const REAGENTS = [
  'Sodium cyanide',
  'Quicklime',
  'Activated carbon',
  'Hydrochloric acid',
  'Caustic soda',
  'Flocculant',
  'Frother MIBC',
  'Collector SIBX',
  'Magnetite',
  'Copper sulphate',
]

export const SUPPLIER_NAMES = [
  'Sandvik Mining Supply', 'Epiroc Regional', 'Caterpillar Dealer Group', 'Komatsu Parts Direct',
  'Weir Minerals Africa', 'Metso Outotec Services', 'FLSmidth Spares', 'Orica Explosives',
  'AECI Mining Chemicals', 'BME Blasting Services', 'Puma Energy Bulk Fuel', 'Total Lubricants',
  'Bearing Man Group', 'Hydraulic and Hose Co', 'Industrial Belting Supplies', 'Bolt and Nut Traders',
  'Continental Conveyor', 'Bridgestone OTR', 'Michelin Earthmover', 'Kal Tire Mining',
  'Rand Safety Wear', 'Dromex PPE', 'MSA Safety Distributors', 'Drager Gas Detection',
  'SGS Analytical Labs', 'ALS Geochemistry', 'Intertek Minerals', 'Bureau Veritas Inspection',
  'Aggreko Power Rental', 'Cummins Power Systems', 'ABB Electrification', 'Schneider Electric Mining',
  'Barloworld Equipment', 'Bell Equipment Services', 'Liebherr Mining Support', 'Hitachi Construction',
  'Multotec Screening', 'Kwatani Vibrating Screens', 'Thyssenkrupp Materials', 'Elgin Brown Rail',
]

export const CONTRACTOR_NAMES: readonly (readonly [string, string])[] = [
  ['Murray and Roberts Cementation', 'Shaft sinking and underground development'],
  ['Redpath Mining Services', 'Underground development and raiseboring'],
  ['Thiess Open Cut', 'Contract mining - overburden removal'],
  ['Moolman Mining', 'Load and haul contract mining'],
  ['Boart Longyear Drilling', 'Exploration and grade control drilling'],
  ['Master Drilling', 'Raiseboring and blind shaft drilling'],
  ['Orica Blasting Services', 'Explosives supply and shotfiring'],
  ['Bidvest Protea Coin', 'Site security and asset protection'],
  ['Fraser Alexander Tailings', 'Tailings deposition and management'],
  ['Enviro Rehab Solutions', 'Rehabilitation and revegetation'],
]

export const CUSTOMER_NAMES: readonly (readonly [string, string, string])[] = [
  ['Rand Refinery', 'refinery', 'South Africa'],
  ['Perth Mint', 'refinery', 'Australia'],
  ['Metalor Technologies', 'refinery', 'Switzerland'],
  ['Eskom Generation', 'utility', 'South Africa'],
  ['Tata Power Trading', 'utility', 'India'],
  ['Nippon Steel', 'steel_mill', 'Japan'],
  ['POSCO Trading', 'steel_mill', 'South Korea'],
  ['Glencore Coal Marketing', 'trader', 'Switzerland'],
  ['Vitol Bulk', 'trader', 'Singapore'],
  ['Trafigura Minerals', 'trader', 'Singapore'],
  ['Aurubis Smelting', 'smelter', 'Germany'],
  ['Jiangxi Copper Import', 'smelter', 'China'],
  ['Adani Global', 'trader', 'India'],
  ['Domestic Cement Works', 'domestic', 'South Africa'],
  ['Regional Power Utility', 'utility', 'Zambia'],
]
