import type { EntityConfig } from '@/components/data/EntityPage'

/**
 * The entity registry.
 *
 * Column types, allowed values and foreign keys are read from the live
 * catalog at runtime (see db/introspect.ts), so an entry here only makes
 * presentation choices: which columns lead the list, what can be filtered,
 * and how the screen is named. Adding a table to the platform is a few
 * lines rather than a new page.
 */
const defs: EntityConfig[] = [
  /* ------------------------------------------------------------ Operations */
  {
    slug: 'production-records',
    table: 'production_records',
    title: 'Production records',
    singular: 'Production record',
    description: 'Shift level tonnes, grade and destination for every source area. The atomic fact behind every production report.',
    listColumns: ['record_date', 'mine_id', 'mining_area_id', 'shift_type', 'material', 'tonnes', 'grade', 'ash_pct', 'destination', 'truck_loads', 'approved'],
    filterColumns: ['mine_id', 'material', 'shift_type', 'destination'],
    searchColumns: ['destination', 'entered_by', 'destination_ref'],
    defaultSort: { column: 'record_date', dir: 'desc' },
  },
  {
    slug: 'mine-plans',
    table: 'mine_plans',
    title: 'Mine plans',
    singular: 'Mine plan',
    description: 'Approved plans by horizon. Actuals are measured against the plan covering the record date.',
    listColumns: ['code', 'name', 'mine_id', 'horizon', 'period_start', 'period_end', 'ore_tonnes', 'waste_tonnes', 'coal_tonnes', 'strip_ratio', 'status'],
    filterColumns: ['mine_id', 'horizon', 'status'],
    defaultSort: { column: 'period_start', dir: 'desc' },
  },
  {
    slug: 'shifts',
    table: 'shifts',
    title: 'Shifts',
    singular: 'Shift',
    description: 'The shift register: crews, supervisors, headcount and handover notes.',
    listColumns: ['shift_date', 'shift_type', 'mine_id', 'crew_id', 'supervisor_employee_id', 'planned_headcount', 'actual_headcount', 'status', 'weather'],
    filterColumns: ['mine_id', 'shift_type', 'status', 'crew_id'],
    searchColumns: ['handover_notes', 'weather'],
    defaultSort: { column: 'shift_date', dir: 'desc' },
  },
  {
    slug: 'shift-logs',
    table: 'shift_logs',
    title: 'Shift log book',
    singular: 'Log entry',
    description: 'Statutory logbook and handover entries.',
    listColumns: ['logged_at', 'mine_id', 'log_type', 'author', 'entry', 'requires_action', 'acknowledged_by'],
    filterColumns: ['mine_id', 'log_type'],
    searchColumns: ['entry', 'author'],
    defaultSort: { column: 'logged_at', dir: 'desc' },
  },
  {
    slug: 'development',
    table: 'development_records',
    title: 'Development advance',
    singular: 'Development record',
    description: 'Underground heading advance, support installed and cycle times.',
    listColumns: ['record_date', 'mine_id', 'heading_code', 'advance_m', 'cumulative_m', 'tonnes_broken', 'bolts_installed', 'shotcrete_m3', 'cycle_hours', 'crew_id'],
    filterColumns: ['mine_id', 'crew_id'],
    searchColumns: ['heading_code', 'support_installed', 'comments'],
    defaultSort: { column: 'record_date', dir: 'desc' },
  },
  {
    slug: 'drill-patterns',
    table: 'drill_patterns',
    title: 'Drill patterns',
    singular: 'Drill pattern',
    description: 'Blast pattern designs: burden, spacing, hole geometry and powder factor.',
    listColumns: ['pattern_code', 'mine_id', 'mining_area_id', 'burden_m', 'spacing_m', 'hole_diameter_mm', 'hole_depth_m', 'hole_count', 'total_metres', 'powder_factor_kg_t', 'status'],
    filterColumns: ['mine_id', 'status'],
    searchColumns: ['pattern_code', 'rock_type', 'designed_by'],
    defaultSort: { column: 'id', dir: 'desc' },
  },
  {
    slug: 'drilling',
    table: 'drilling_records',
    title: 'Production drilling',
    singular: 'Drilling record',
    description: 'Metres drilled per rig and shift, with penetration rates and consumables.',
    listColumns: ['record_date', 'mine_id', 'pattern_id', 'asset_id', 'holes_drilled', 'metres_drilled', 'penetration_rate_m_h', 'bits_consumed', 'delays_hours'],
    filterColumns: ['mine_id', 'asset_id'],
    defaultSort: { column: 'record_date', dir: 'desc' },
  },
  {
    slug: 'blasts',
    table: 'blasts',
    title: 'Blast register',
    singular: 'Blast',
    description: 'Every blast fired, with explosive quantities, vibration monitoring and misfire records.',
    listColumns: ['blast_number', 'fired_at', 'mine_id', 'blast_type', 'holes_charged', 'total_explosive_kg', 'tonnes_blasted', 'powder_factor_kg_t', 'ppv_mm_s', 'misfires', 'status'],
    filterColumns: ['mine_id', 'blast_type', 'status'],
    searchColumns: ['blast_number', 'notes'],
    defaultSort: { column: 'fired_at', dir: 'desc' },
  },
  {
    slug: 'explosives-magazines',
    table: 'explosives_magazines',
    title: 'Explosives magazines',
    singular: 'Magazine',
    description: 'Licensed magazines, capacities and custodians.',
    listColumns: ['code', 'name', 'site_id', 'magazine_type', 'licence_no', 'licence_expiry', 'capacity_kg', 'status'],
    filterColumns: ['site_id', 'magazine_type', 'status'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'explosives-transactions',
    table: 'explosives_transactions',
    title: 'Explosives movements',
    singular: 'Explosives transaction',
    description: 'Receipts, issues and returns against each magazine, with the running balance required by law.',
    listColumns: ['transacted_at', 'magazine_id', 'direction', 'product', 'product_class', 'quantity', 'unit', 'balance_after', 'reference'],
    filterColumns: ['magazine_id', 'direction', 'product_class'],
    searchColumns: ['product', 'reference', 'recorded_by'],
    defaultSort: { column: 'transacted_at', dir: 'desc' },
  },
  {
    slug: 'haulage',
    table: 'haulage_cycles',
    title: 'Haulage cycles',
    singular: 'Haulage cycle',
    description: 'Truck cycle times broken into queue, load, haul, dump and return.',
    listColumns: ['cycle_start', 'truck_asset_id', 'loader_asset_id', 'material', 'payload_tonnes', 'distance_km', 'queue_minutes', 'cycle_minutes', 'fuel_litres'],
    filterColumns: ['mine_id', 'material', 'truck_asset_id'],
    defaultSort: { column: 'cycle_start', dir: 'desc' },
  },
  {
    slug: 'stockpiles',
    table: 'stockpiles',
    title: 'Stockpiles',
    singular: 'Stockpile',
    description: 'Live balances and average quality for every ROM, product and waste stockpile.',
    listColumns: ['code', 'name', 'site_id', 'material', 'product_grade', 'current_tonnes', 'capacity_tonnes', 'average_grade', 'average_ash_pct', 'average_cv_kcal_kg', 'status'],
    filterColumns: ['site_id', 'material', 'status'],
    defaultSort: { column: 'current_tonnes', dir: 'desc' },
  },
  {
    slug: 'stockpile-movements',
    table: 'stockpile_movements',
    title: 'Stockpile movements',
    singular: 'Stockpile movement',
    listColumns: ['moved_at', 'stockpile_id', 'direction', 'tonnes', 'grade', 'ash_pct', 'source', 'destination', 'balance_after'],
    filterColumns: ['stockpile_id', 'direction'],
    defaultSort: { column: 'moved_at', dir: 'desc' },
  },
  {
    slug: 'ventilation',
    table: 'ventilation_readings',
    title: 'Ventilation readings',
    singular: 'Ventilation reading',
    description: 'Airflow, temperature and dust at each ventilation station.',
    listColumns: ['measured_at', 'mine_id', 'station_code', 'air_velocity_m_s', 'air_quantity_m3_s', 'dry_bulb_c', 'wet_bulb_c', 'dust_mg_m3', 'compliant'],
    filterColumns: ['mine_id'],
    searchColumns: ['station_code', 'measured_by'],
    defaultSort: { column: 'measured_at', dir: 'desc' },
  },
  {
    slug: 'gas-readings',
    table: 'gas_readings',
    title: 'Gas monitoring',
    singular: 'Gas reading',
    description: 'Methane, carbon monoxide and oxygen readings with alarm state. The most safety-critical stream underground.',
    listColumns: ['measured_at', 'mine_id', 'station_code', 'source', 'ch4_pct', 'co_ppm', 'co2_pct', 'o2_pct', 'temperature_c', 'alarm_level'],
    filterColumns: ['mine_id', 'alarm_level', 'source'],
    searchColumns: ['station_code', 'action_taken'],
    defaultSort: { column: 'measured_at', dir: 'desc' },
  },
  {
    slug: 'ground-support',
    table: 'ground_support_records',
    title: 'Ground support',
    singular: 'Ground support record',
    listColumns: ['installed_on', 'mine_id', 'mining_area_id', 'support_type', 'quantity', 'unit', 'length_m', 'pull_test_kn', 'qa_result'],
    filterColumns: ['mine_id', 'support_type', 'qa_result'],
    defaultSort: { column: 'installed_on', dir: 'desc' },
  },
  {
    slug: 'dewatering',
    table: 'dewatering_records',
    title: 'Dewatering',
    singular: 'Dewatering record',
    listColumns: ['record_date', 'mine_id', 'asset_id', 'volume_pumped_m3', 'pump_hours', 'water_level_m', 'discharge_point', 'ph', 'turbidity_ntu'],
    filterColumns: ['mine_id'],
    defaultSort: { column: 'record_date', dir: 'desc' },
  },

  /* --------------------------------------------------------------- Geology */
  {
    slug: 'exploration-projects',
    table: 'exploration_projects',
    title: 'Exploration projects',
    singular: 'Exploration project',
    listColumns: ['code', 'name', 'site_id', 'commodity', 'stage', 'area_km2', 'budget', 'spend_to_date', 'geologist', 'status'],
    filterColumns: ['site_id', 'commodity', 'stage', 'status'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'drill-programs',
    table: 'drill_programs',
    title: 'Drill programmes',
    singular: 'Drill programme',
    listColumns: ['code', 'name', 'mine_id', 'purpose', 'drill_method', 'planned_holes', 'actual_holes', 'planned_metres', 'actual_metres', 'cost_per_metre', 'status'],
    filterColumns: ['mine_id', 'purpose', 'drill_method', 'status'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'drillholes',
    table: 'drillholes',
    title: 'Drillholes',
    singular: 'Drillhole',
    description: 'Collar positions, orientation, depth and logging status for every hole.',
    listColumns: ['hole_id', 'program_id', 'mine_id', 'hole_type', 'easting', 'northing', 'azimuth_deg', 'dip_deg', 'final_depth_m', 'recovery_pct', 'status'],
    filterColumns: ['mine_id', 'hole_type', 'status', 'program_id'],
    searchColumns: ['hole_id', 'logged_by', 'comments'],
    defaultSort: { column: 'hole_id', dir: 'desc' },
  },
  {
    slug: 'lithology',
    table: 'lithology_intervals',
    title: 'Geological logging',
    singular: 'Lithology interval',
    listColumns: ['drillhole_id', 'from_m', 'to_m', 'lithology', 'alteration', 'mineralisation', 'weathering', 'rqd_pct', 'seam_name'],
    filterColumns: ['weathering'],
    searchColumns: ['lithology', 'alteration', 'mineralisation', 'seam_name'],
    defaultSort: { column: 'id', dir: 'desc' },
  },
  {
    slug: 'samples',
    table: 'samples',
    title: 'Samples',
    singular: 'Sample',
    listColumns: ['sample_no', 'drillhole_id', 'batch_id', 'sample_type', 'from_m', 'to_m', 'length_m', 'weight_kg', 'qaqc_type', 'collected_on', 'status'],
    filterColumns: ['sample_type', 'qaqc_type', 'status', 'batch_id'],
    searchColumns: ['sample_no', 'collected_by'],
    defaultSort: { column: 'id', dir: 'desc' },
  },
  {
    slug: 'sample-batches',
    table: 'sample_batches',
    title: 'Laboratory batches',
    singular: 'Sample batch',
    listColumns: ['batch_no', 'laboratory', 'sample_count', 'dispatched_on', 'received_on', 'results_on', 'turnaround_days', 'cost', 'status'],
    filterColumns: ['status'],
    searchColumns: ['batch_no', 'laboratory'],
    defaultSort: { column: 'dispatched_on', dir: 'desc' },
  },
  {
    slug: 'assays',
    table: 'assays',
    title: 'Assay results',
    singular: 'Assay',
    listColumns: ['sample_id', 'element', 'value', 'unit', 'method', 'laboratory', 'analysed_on', 'below_detection', 'is_repeat'],
    filterColumns: ['element', 'unit'],
    searchColumns: ['element', 'method', 'laboratory'],
    defaultSort: { column: 'id', dir: 'desc' },
  },
  {
    slug: 'coal-quality',
    table: 'coal_quality_results',
    title: 'Coal quality',
    singular: 'Coal quality result',
    description: 'Proximate and ultimate analysis on the reported basis.',
    listColumns: ['sample_id', 'basis', 'moisture_pct', 'ash_pct', 'volatile_matter_pct', 'fixed_carbon_pct', 'sulphur_pct', 'calorific_value_kcal_kg', 'hgi', 'analysed_on'],
    filterColumns: ['basis'],
    defaultSort: { column: 'id', dir: 'desc' },
  },
  {
    slug: 'resource-blocks',
    table: 'resource_blocks',
    title: 'Block model',
    singular: 'Resource block',
    description: 'Block level tonnes and grade driving grade control and short term planning.',
    listColumns: ['block_code', 'mine_id', 'mining_area_id', 'tonnes', 'grade_primary', 'grade_unit', 'ash_pct', 'classification', 'ore_type', 'recovery_pct', 'is_ore', 'mined'],
    filterColumns: ['mine_id', 'classification', 'is_ore', 'mined'],
    searchColumns: ['block_code', 'ore_type'],
    defaultSort: { column: 'tonnes', dir: 'desc' },
  },
  {
    slug: 'resource-statements',
    table: 'resource_statements',
    title: 'Resources and reserves',
    singular: 'Resource statement',
    description: 'Signed off resource and reserve statements by reporting code.',
    listColumns: ['as_at', 'mine_id', 'category', 'reporting_code', 'tonnes', 'grade', 'grade_unit', 'contained_metal', 'contained_unit', 'cut_off_grade', 'competent_person'],
    filterColumns: ['mine_id', 'category', 'reporting_code'],
    defaultSort: { column: 'as_at', dir: 'desc' },
  },
  {
    slug: 'geotechnical',
    table: 'geotech_monitoring',
    title: 'Geotechnical monitoring',
    singular: 'Geotechnical reading',
    description: 'Slope and ground movement instrumentation with alarm thresholds.',
    listColumns: ['measured_at', 'mine_id', 'station_code', 'instrument_type', 'displacement_mm', 'velocity_mm_day', 'pore_pressure_kpa', 'alarm_level', 'action_taken'],
    filterColumns: ['mine_id', 'instrument_type', 'alarm_level'],
    searchColumns: ['station_code', 'action_taken'],
    defaultSort: { column: 'measured_at', dir: 'desc' },
  },
  {
    slug: 'survey-pickups',
    table: 'survey_pickups',
    title: 'Survey pickups',
    singular: 'Survey pickup',
    description: 'Surveyed volumes reconciled against claimed production.',
    listColumns: ['pickup_date', 'mine_id', 'mining_area_id', 'method', 'material', 'volume_m3', 'tonnes', 'reconciled_tonnes', 'variance_pct', 'surveyor'],
    filterColumns: ['mine_id', 'material', 'method'],
    defaultSort: { column: 'pickup_date', dir: 'desc' },
  },

  /* ------------------------------------------------------------ Processing */
  {
    slug: 'plants',
    table: 'plants',
    title: 'Plants',
    singular: 'Plant',
    listColumns: ['code', 'name', 'site_id', 'plant_type', 'commodity', 'design_throughput_tph', 'design_recovery_pct', 'commissioned_on', 'manager', 'status'],
    filterColumns: ['site_id', 'plant_type', 'status'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'plant-circuits',
    table: 'plant_circuits',
    title: 'Plant circuits',
    singular: 'Circuit',
    listColumns: ['code', 'name', 'plant_id', 'stage', 'design_capacity_tph', 'status'],
    filterColumns: ['plant_id', 'stage', 'status'],
    defaultSort: { column: 'plant_id', dir: 'asc' },
  },
  {
    slug: 'plant-runs',
    table: 'plant_runs',
    title: 'Plant runs',
    singular: 'Plant run',
    description: 'Daily metallurgical accounting: feed, product, recovery and utilities.',
    listColumns: ['run_date', 'plant_id', 'operating_hours', 'downtime_hours', 'feed_tonnes', 'feed_grade', 'throughput_tph', 'product_tonnes', 'recovery_pct', 'yield_pct', 'metal_produced', 'power_kwh'],
    filterColumns: ['plant_id'],
    searchColumns: ['comments'],
    defaultSort: { column: 'run_date', dir: 'desc' },
  },
  {
    slug: 'reagents',
    table: 'reagent_consumption',
    title: 'Reagent consumption',
    singular: 'Reagent record',
    listColumns: ['consumed_on', 'plant_id', 'reagent', 'quantity', 'unit', 'dosage_g_t', 'unit_cost', 'total_cost'],
    filterColumns: ['plant_id'],
    searchColumns: ['reagent'],
    defaultSort: { column: 'consumed_on', dir: 'desc' },
  },
  {
    slug: 'met-samples',
    table: 'metallurgical_samples',
    title: 'Metallurgical samples',
    singular: 'Metallurgical sample',
    listColumns: ['sampled_at', 'plant_id', 'circuit_id', 'sample_point', 'stream_type', 'grade', 'grade_unit', 'solids_pct', 'p80_microns', 'ph', 'ash_pct'],
    filterColumns: ['plant_id', 'stream_type'],
    searchColumns: ['sample_point', 'analysed_by'],
    defaultSort: { column: 'sampled_at', dir: 'desc' },
  },
  {
    slug: 'gold-pours',
    table: 'gold_pours',
    title: 'Gold pours',
    singular: 'Gold pour',
    description: 'Gold room production with chain of custody.',
    listColumns: ['pour_number', 'poured_at', 'plant_id', 'source', 'bars_count', 'gross_weight_g', 'fineness', 'fine_gold_oz', 'security_seal_no', 'status'],
    filterColumns: ['plant_id', 'source', 'status'],
    searchColumns: ['pour_number', 'witnessed_by', 'security_seal_no'],
    defaultSort: { column: 'poured_at', dir: 'desc' },
  },
  {
    slug: 'bullion-shipments',
    table: 'bullion_shipments',
    title: 'Bullion shipments',
    singular: 'Bullion shipment',
    listColumns: ['shipment_no', 'shipped_at', 'refinery', 'carrier', 'bars_count', 'fine_gold_oz', 'declared_value', 'settlement_oz', 'variance_oz', 'status'],
    filterColumns: ['status'],
    searchColumns: ['shipment_no', 'refinery', 'carrier'],
    defaultSort: { column: 'shipped_at', dir: 'desc' },
  },
  {
    slug: 'product-specs',
    table: 'product_specs',
    title: 'Product specifications',
    singular: 'Product spec',
    listColumns: ['code', 'name', 'commodity', 'min_cv_kcal_kg', 'max_ash_pct', 'max_moisture_pct', 'max_sulphur_pct', 'min_grade', 'active'],
    filterColumns: ['commodity', 'active'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'quality-samples',
    table: 'quality_samples',
    title: 'Product quality',
    singular: 'Quality sample',
    description: 'Saleable product sampling against contractual specification.',
    listColumns: ['sample_no', 'sampled_at', 'site_id', 'product_spec_id', 'sample_point', 'cv_kcal_kg', 'ash_pct', 'moisture_pct', 'sulphur_pct', 'grade', 'within_spec'],
    filterColumns: ['site_id', 'product_spec_id', 'within_spec'],
    searchColumns: ['sample_no', 'sample_point', 'deviation_notes'],
    defaultSort: { column: 'sampled_at', dir: 'desc' },
  },
  {
    slug: 'tailings-facilities',
    table: 'tailings_facilities',
    title: 'Tailings facilities',
    singular: 'Tailings facility',
    listColumns: ['code', 'name', 'site_id', 'facility_type', 'consequence_category', 'design_capacity_m3', 'stored_volume_m3', 'freeboard_m', 'min_freeboard_m', 'next_audit_on', 'status'],
    filterColumns: ['site_id', 'facility_type', 'consequence_category', 'status'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'tailings-readings',
    table: 'tailings_readings',
    title: 'Tailings monitoring',
    singular: 'Tailings reading',
    listColumns: ['measured_at', 'facility_id', 'pond_level_m', 'freeboard_m', 'phreatic_surface_m', 'seepage_l_s', 'displacement_mm', 'ph', 'cn_wad_ppm', 'alarm_level'],
    filterColumns: ['facility_id', 'alarm_level'],
    defaultSort: { column: 'measured_at', dir: 'desc' },
  },

  /* ----------------------------------------------------------- Maintenance */
  {
    slug: 'assets',
    table: 'assets',
    title: 'Asset register',
    singular: 'Asset',
    description: 'Every mobile and fixed asset, its ownership, criticality and current state.',
    listColumns: ['asset_no', 'name', 'asset_type', 'site_id', 'mine_id', 'manufacturer', 'model', 'ownership', 'capacity_value', 'criticality', 'status'],
    filterColumns: ['site_id', 'mine_id', 'asset_type', 'status', 'criticality', 'ownership'],
    searchColumns: ['asset_no', 'name', 'model', 'serial_no', 'registration_no'],
    defaultSort: { column: 'asset_no', dir: 'asc' },
  },
  {
    slug: 'asset-categories',
    table: 'asset_categories',
    title: 'Asset categories',
    singular: 'Asset category',
    listColumns: ['code', 'name', 'class', 'meter_type'],
    filterColumns: ['class'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'work-orders',
    table: 'work_orders',
    title: 'Work orders',
    singular: 'Work order',
    description: 'Planned and reactive maintenance with costs, downtime and root cause.',
    listColumns: ['wo_number', 'title', 'asset_id', 'wo_type', 'priority', 'status', 'reported_at', 'scheduled_start', 'downtime_hours', 'total_cost', 'assigned_to_employee_id'],
    filterColumns: ['site_id', 'wo_type', 'priority', 'status', 'asset_id'],
    searchColumns: ['wo_number', 'title', 'description', 'root_cause'],
    defaultSort: { column: 'reported_at', dir: 'desc' },
  },
  {
    slug: 'work-order-tasks',
    table: 'work_order_tasks',
    title: 'Work order tasks',
    singular: 'Task',
    listColumns: ['work_order_id', 'seq', 'description', 'trade', 'estimated_hours', 'actual_hours', 'employee_id', 'status', 'completed_at'],
    filterColumns: ['status'],
    searchColumns: ['description', 'trade'],
    defaultSort: { column: 'id', dir: 'desc' },
  },
  {
    slug: 'work-order-parts',
    table: 'work_order_parts',
    title: 'Work order parts',
    singular: 'Part line',
    listColumns: ['work_order_id', 'item_id', 'part_number', 'description', 'quantity', 'unit_cost', 'line_cost', 'issued_at', 'status'],
    filterColumns: ['status'],
    searchColumns: ['part_number', 'description'],
    defaultSort: { column: 'id', dir: 'desc' },
  },
  {
    slug: 'maintenance-plans',
    table: 'maintenance_plans',
    title: 'Maintenance plans',
    singular: 'Maintenance plan',
    description: 'Preventive strategy per asset, driven by hours, kilometres or calendar.',
    listColumns: ['code', 'name', 'asset_id', 'service_type', 'interval_hours', 'interval_days', 'last_done_at', 'next_due_at', 'next_due_meter', 'estimated_hours', 'active'],
    filterColumns: ['service_type', 'active', 'asset_id'],
    searchColumns: ['code', 'name'],
    defaultSort: { column: 'next_due_at', dir: 'asc' },
  },
  {
    slug: 'downtime',
    table: 'downtime_events',
    title: 'Downtime events',
    singular: 'Downtime event',
    description: 'Every hour an asset was not available, and why.',
    listColumns: ['started_at', 'asset_id', 'category', 'reason', 'duration_hours', 'is_availability_loss', 'work_order_id', 'recorded_by'],
    filterColumns: ['asset_id', 'category', 'is_availability_loss'],
    searchColumns: ['reason', 'recorded_by'],
    defaultSort: { column: 'started_at', dir: 'desc' },
  },
  {
    slug: 'meter-readings',
    table: 'meter_readings',
    title: 'Meter readings',
    singular: 'Meter reading',
    listColumns: ['reading_at', 'asset_id', 'meter_type', 'reading', 'source', 'recorded_by'],
    filterColumns: ['asset_id', 'meter_type', 'source'],
    defaultSort: { column: 'reading_at', dir: 'desc' },
  },
  {
    slug: 'fuel',
    table: 'fuel_transactions',
    title: 'Fuel and lubricants',
    singular: 'Fuel transaction',
    listColumns: ['transacted_at', 'site_id', 'asset_id', 'fuel_type', 'litres', 'meter_reading', 'unit_price', 'total_cost', 'bay', 'source'],
    filterColumns: ['site_id', 'fuel_type', 'source', 'asset_id'],
    defaultSort: { column: 'transacted_at', dir: 'desc' },
  },
  {
    slug: 'tyres',
    table: 'tyre_records',
    title: 'Tyre management',
    singular: 'Tyre record',
    listColumns: ['serial_no', 'asset_id', 'brand', 'size', 'position_code', 'fitted_at', 'removed_at', 'hours_run', 'tread_depth_mm', 'removal_reason', 'status'],
    filterColumns: ['asset_id', 'brand', 'status', 'removal_reason'],
    searchColumns: ['serial_no', 'brand', 'size'],
    defaultSort: { column: 'fitted_at', dir: 'desc' },
  },
  {
    slug: 'equipment-inspections',
    table: 'equipment_inspections',
    title: 'Equipment inspections',
    singular: 'Equipment inspection',
    description: 'Operator pre-start and statutory equipment checks.',
    listColumns: ['inspected_at', 'asset_id', 'inspection_type', 'employee_id', 'result', 'defects_found', 'defect_notes', 'work_order_id'],
    filterColumns: ['asset_id', 'inspection_type', 'result'],
    searchColumns: ['defect_notes'],
    defaultSort: { column: 'inspected_at', dir: 'desc' },
  },
  {
    slug: 'failure-codes',
    table: 'failure_codes',
    title: 'Failure codes',
    singular: 'Failure code',
    listColumns: ['code', 'name', 'system', 'severity'],
    filterColumns: ['system', 'severity'],
    defaultSort: { column: 'code', dir: 'asc' },
  },

  /* ------------------------------------------------------------- Workforce */
  {
    slug: 'employees',
    table: 'employees',
    title: 'Employees',
    singular: 'Employee',
    description: 'The people register: roles, employment terms, location and status.',
    listColumns: ['employee_no', 'first_name', 'last_name', 'job_title', 'occupation_group', 'site_id', 'department_id', 'employment_type', 'work_location', 'hired_on', 'status'],
    filterColumns: ['site_id', 'department_id', 'status', 'employment_type', 'work_location', 'occupation_group', 'contractor_id'],
    searchColumns: ['employee_no', 'first_name', 'last_name', 'job_title', 'email'],
    defaultSort: { column: 'last_name', dir: 'asc' },
  },
  {
    slug: 'crews',
    table: 'crews',
    title: 'Crews',
    singular: 'Crew',
    listColumns: ['code', 'name', 'site_id', 'mine_id', 'shift_pattern_id', 'supervisor_employee_id', 'headcount_target', 'active'],
    filterColumns: ['site_id', 'mine_id', 'active'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'crew-members',
    table: 'crew_members',
    title: 'Crew membership',
    singular: 'Crew member',
    listColumns: ['crew_id', 'employee_id', 'role_in_crew', 'joined_on', 'left_on'],
    filterColumns: ['crew_id'],
    defaultSort: { column: 'joined_on', dir: 'desc' },
  },
  {
    slug: 'shift-patterns',
    table: 'shift_patterns',
    title: 'Shift patterns',
    singular: 'Shift pattern',
    listColumns: ['code', 'name', 'cycle_days', 'shift_hours', 'shifts_per_day', 'rotation', 'description'],
    filterColumns: ['rotation'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'attendance',
    table: 'attendance',
    title: 'Attendance',
    singular: 'Attendance record',
    listColumns: ['work_date', 'employee_id', 'clock_in', 'clock_out', 'hours_worked', 'overtime_hours', 'status', 'fitness_check', 'alcohol_test'],
    filterColumns: ['status', 'fitness_check', 'alcohol_test'],
    defaultSort: { column: 'work_date', dir: 'desc' },
  },
  {
    slug: 'tag-board',
    table: 'personnel_on_site',
    title: 'Tag board',
    singular: 'Tag record',
    description: 'Statutory record of who has entered and left the workings.',
    listColumns: ['entered_at', 'exited_at', 'employee_id', 'visitor_name', 'mine_id', 'tag_number', 'lamp_number', 'self_rescuer_no', 'location', 'purpose'],
    filterColumns: ['site_id', 'mine_id'],
    searchColumns: ['visitor_name', 'tag_number', 'location', 'purpose'],
    defaultSort: { column: 'entered_at', dir: 'desc' },
  },
  {
    slug: 'competencies',
    table: 'competencies',
    title: 'Competency types',
    singular: 'Competency',
    listColumns: ['code', 'name', 'category', 'validity_months', 'is_mandatory', 'applies_to'],
    filterColumns: ['category', 'is_mandatory'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'employee-competencies',
    table: 'employee_competencies',
    title: 'Competency records',
    singular: 'Competency record',
    listColumns: ['employee_id', 'competency_id', 'achieved_on', 'expires_on', 'certificate_no', 'assessor', 'status'],
    filterColumns: ['competency_id', 'status'],
    searchColumns: ['certificate_no', 'assessor'],
    defaultSort: { column: 'expires_on', dir: 'asc' },
  },
  {
    slug: 'training-courses',
    table: 'training_courses',
    title: 'Training catalogue',
    singular: 'Course',
    listColumns: ['code', 'name', 'provider', 'duration_hours', 'delivery', 'competency_id', 'cost_per_person', 'active'],
    filterColumns: ['delivery', 'active'],
    searchColumns: ['code', 'name', 'provider'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'training-records',
    table: 'training_records',
    title: 'Training records',
    singular: 'Training record',
    listColumns: ['scheduled_on', 'completed_on', 'employee_id', 'course_id', 'result', 'score', 'trainer', 'cost'],
    filterColumns: ['course_id', 'result'],
    searchColumns: ['trainer', 'notes'],
    defaultSort: { column: 'scheduled_on', dir: 'desc' },
  },
  {
    slug: 'leave',
    table: 'leave_requests',
    title: 'Leave',
    singular: 'Leave request',
    listColumns: ['employee_id', 'leave_type', 'start_date', 'end_date', 'days', 'reason', 'status', 'approved_by'],
    filterColumns: ['leave_type', 'status'],
    defaultSort: { column: 'start_date', dir: 'desc' },
  },
  {
    slug: 'medicals',
    table: 'medical_examinations',
    title: 'Occupational health',
    singular: 'Medical examination',
    listColumns: ['exam_date', 'employee_id', 'exam_type', 'next_due_on', 'provider', 'outcome', 'restrictions', 'hearing_loss_db', 'lung_function_pct'],
    filterColumns: ['exam_type', 'outcome'],
    defaultSort: { column: 'exam_date', dir: 'desc' },
  },
  {
    slug: 'payroll-periods',
    table: 'payroll_periods',
    title: 'Payroll periods',
    singular: 'Payroll period',
    listColumns: ['code', 'period_start', 'period_end', 'pay_date', 'gross_total', 'deductions_total', 'net_total', 'currency', 'status'],
    filterColumns: ['status'],
    defaultSort: { column: 'period_start', dir: 'desc' },
  },
  {
    slug: 'payroll-lines',
    table: 'payroll_lines',
    title: 'Payroll detail',
    singular: 'Payroll line',
    listColumns: ['period_id', 'employee_id', 'normal_hours', 'overtime_hours', 'base_pay', 'overtime_pay', 'production_bonus', 'underground_allowance', 'gross_pay', 'tax', 'net_pay'],
    filterColumns: ['period_id'],
    defaultSort: { column: 'id', dir: 'desc' },
  },
  {
    slug: 'er-cases',
    table: 'employee_relations_cases',
    title: 'Employee relations',
    singular: 'ER case',
    listColumns: ['case_number', 'employee_id', 'case_type', 'opened_on', 'closed_on', 'severity', 'summary', 'status', 'handled_by'],
    filterColumns: ['case_type', 'severity', 'status'],
    searchColumns: ['case_number', 'summary', 'outcome'],
    defaultSort: { column: 'opened_on', dir: 'desc' },
  },
  {
    slug: 'contractors',
    table: 'contractors',
    title: 'Contractors',
    singular: 'Contractor',
    listColumns: ['code', 'name', 'site_id', 'scope_of_work', 'contact_name', 'contract_start', 'contract_end', 'insurance_expiry', 'safety_rating', 'status'],
    filterColumns: ['site_id', 'status', 'safety_rating'],
    searchColumns: ['code', 'name', 'scope_of_work', 'contact_name'],
    defaultSort: { column: 'name', dir: 'asc' },
  },

  /* ------------------------------------------------------------------- HSE */
  {
    slug: 'incidents',
    table: 'incidents',
    title: 'Incidents',
    singular: 'Incident',
    description: 'Injuries, near misses, environmental and property events, with investigation status.',
    listColumns: ['incident_no', 'occurred_at', 'site_id', 'incident_type', 'title', 'potential_severity', 'days_lost', 'reportable_to_regulator', 'status'],
    filterColumns: ['site_id', 'mine_id', 'incident_type', 'status', 'potential_severity', 'reportable_to_regulator'],
    searchColumns: ['incident_no', 'title', 'description', 'root_cause', 'location'],
    defaultSort: { column: 'occurred_at', dir: 'desc' },
  },
  {
    slug: 'actions',
    table: 'corrective_actions',
    title: 'Corrective actions',
    singular: 'Action',
    description: 'Actions raised from any source, tracked to verified close out.',
    listColumns: ['action_no', 'description', 'source_entity', 'priority', 'assigned_to_employee_id', 'raised_on', 'due_on', 'completed_on', 'status', 'effectiveness_rating'],
    filterColumns: ['site_id', 'priority', 'status', 'source_entity', 'action_type'],
    searchColumns: ['action_no', 'description', 'verification_notes'],
    defaultSort: { column: 'due_on', dir: 'asc' },
  },
  {
    slug: 'hazards',
    table: 'hazards',
    title: 'Hazard register',
    singular: 'Hazard',
    listColumns: ['hazard_code', 'title', 'category', 'is_principal_hazard', 'inherent_risk', 'residual_risk', 'risk_rating', 'owner', 'next_review_on', 'status'],
    filterColumns: ['site_id', 'category', 'risk_rating', 'is_principal_hazard', 'status'],
    searchColumns: ['hazard_code', 'title', 'description', 'controls'],
    defaultSort: { column: 'residual_risk', dir: 'desc' },
  },
  {
    slug: 'risk-assessments',
    table: 'risk_assessments',
    title: 'Risk assessments',
    singular: 'Risk assessment',
    listColumns: ['reference', 'title', 'assessment_type', 'activity', 'location', 'assessed_on', 'highest_residual_risk', 'next_review_on', 'status'],
    filterColumns: ['site_id', 'assessment_type', 'status', 'highest_residual_risk'],
    searchColumns: ['reference', 'title', 'activity', 'location'],
    defaultSort: { column: 'assessed_on', dir: 'desc' },
  },
  {
    slug: 'observations',
    table: 'safety_observations',
    title: 'Safety observations',
    singular: 'Observation',
    listColumns: ['observed_at', 'site_id', 'observation_type', 'category', 'location', 'description', 'is_unsafe', 'risk_rating', 'status'],
    filterColumns: ['site_id', 'observation_type', 'is_unsafe', 'risk_rating', 'status'],
    searchColumns: ['description', 'location', 'category'],
    defaultSort: { column: 'observed_at', dir: 'desc' },
  },
  {
    slug: 'permits',
    table: 'permits_to_work',
    title: 'Permits to work',
    singular: 'Permit',
    listColumns: ['permit_no', 'permit_type', 'work_description', 'location', 'valid_from', 'valid_to', 'gas_test_required', 'status'],
    filterColumns: ['site_id', 'permit_type', 'status'],
    searchColumns: ['permit_no', 'work_description', 'location', 'isolation_ref'],
    defaultSort: { column: 'valid_from', dir: 'desc' },
  },
  {
    slug: 'hse-inspections',
    table: 'hse_inspections',
    title: 'HSE inspections',
    singular: 'HSE inspection',
    listColumns: ['inspection_no', 'inspection_type', 'area', 'scheduled_on', 'performed_on', 'inspector', 'score_pct', 'findings_count', 'critical_findings', 'result', 'status'],
    filterColumns: ['site_id', 'inspection_type', 'status', 'result'],
    searchColumns: ['inspection_no', 'area', 'inspector'],
    defaultSort: { column: 'scheduled_on', dir: 'desc' },
  },
  {
    slug: 'toolbox-talks',
    table: 'toolbox_talks',
    title: 'Toolbox talks',
    singular: 'Toolbox talk',
    listColumns: ['held_at', 'site_id', 'crew_id', 'topic', 'presenter', 'attendees_count', 'duration_minutes', 'issues_raised'],
    filterColumns: ['site_id', 'crew_id'],
    searchColumns: ['topic', 'presenter', 'key_points'],
    defaultSort: { column: 'held_at', dir: 'desc' },
  },
  {
    slug: 'ppe',
    table: 'ppe_issues',
    title: 'PPE issues',
    singular: 'PPE issue',
    listColumns: ['issued_on', 'employee_id', 'ppe_type', 'quantity', 'size', 'serial_no', 'replacement_due', 'cost', 'condition'],
    filterColumns: ['ppe_type', 'condition'],
    searchColumns: ['serial_no', 'size'],
    defaultSort: { column: 'issued_on', dir: 'desc' },
  },
  {
    slug: 'emergency-drills',
    table: 'emergency_drills',
    title: 'Emergency drills',
    singular: 'Drill',
    listColumns: ['held_at', 'site_id', 'mine_id', 'drill_type', 'participants', 'evacuation_minutes', 'target_minutes', 'outcome', 'led_by'],
    filterColumns: ['site_id', 'drill_type', 'outcome'],
    searchColumns: ['observations', 'led_by'],
    defaultSort: { column: 'held_at', dir: 'desc' },
  },

  /* ----------------------------------------------------------- Environment */
  {
    slug: 'environmental-monitoring',
    table: 'environmental_monitoring',
    title: 'Environmental monitoring',
    singular: 'Monitoring result',
    description: 'Water, air, dust, noise and vibration results against licence limits.',
    listColumns: ['measured_at', 'site_id', 'station_code', 'medium', 'parameter', 'value', 'unit', 'limit_value', 'compliant', 'laboratory'],
    filterColumns: ['site_id', 'medium', 'compliant'],
    searchColumns: ['station_code', 'parameter', 'laboratory'],
    defaultSort: { column: 'measured_at', dir: 'desc' },
  },
  {
    slug: 'water-balance',
    table: 'water_balance',
    title: 'Water balance',
    singular: 'Water balance record',
    listColumns: ['record_date', 'site_id', 'abstraction_m3', 'rainfall_mm', 'recycled_m3', 'discharged_m3', 'process_use_m3', 'dust_suppression_m3', 'storage_m3', 'licence_limit_m3'],
    filterColumns: ['site_id'],
    defaultSort: { column: 'record_date', dir: 'desc' },
  },
  {
    slug: 'energy',
    table: 'energy_records',
    title: 'Energy and emissions',
    singular: 'Energy record',
    listColumns: ['record_date', 'site_id', 'source', 'consumption_kwh', 'demand_kw', 'cost', 'co2e_tonnes', 'scope'],
    filterColumns: ['site_id', 'source', 'scope'],
    defaultSort: { column: 'record_date', dir: 'desc' },
  },
  {
    slug: 'waste',
    table: 'waste_records',
    title: 'Waste management',
    singular: 'Waste record',
    listColumns: ['record_date', 'site_id', 'waste_stream', 'quantity', 'unit', 'disposal_method', 'contractor_id', 'manifest_no', 'cost'],
    filterColumns: ['site_id', 'waste_stream', 'disposal_method'],
    searchColumns: ['manifest_no'],
    defaultSort: { column: 'record_date', dir: 'desc' },
  },
  {
    slug: 'rehabilitation',
    table: 'rehabilitation_areas',
    title: 'Rehabilitation',
    singular: 'Rehabilitation area',
    listColumns: ['code', 'name', 'site_id', 'rehab_type', 'disturbed_hectares', 'rehabilitated_hectares', 'vegetation_cover_pct', 'provision_cost', 'spend_to_date', 'status'],
    filterColumns: ['site_id', 'rehab_type', 'status'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'community',
    table: 'community_engagements',
    title: 'Community relations',
    singular: 'Engagement',
    listColumns: ['reference', 'occurred_on', 'site_id', 'engagement_type', 'stakeholder', 'community', 'description', 'amount', 'status'],
    filterColumns: ['site_id', 'engagement_type', 'status'],
    searchColumns: ['reference', 'stakeholder', 'community', 'description'],
    defaultSort: { column: 'occurred_on', dir: 'desc' },
  },

  /* ---------------------------------------------------------- Supply chain */
  {
    slug: 'items',
    table: 'items',
    title: 'Item catalogue',
    singular: 'Item',
    listColumns: ['item_code', 'name', 'category', 'uom', 'manufacturer', 'preferred_supplier_id', 'unit_cost', 'reorder_point', 'lead_time_days', 'is_critical', 'active'],
    filterColumns: ['category', 'is_critical', 'hazardous', 'active', 'preferred_supplier_id'],
    searchColumns: ['item_code', 'name', 'description', 'manufacturer_part_no'],
    defaultSort: { column: 'item_code', dir: 'asc' },
  },
  {
    slug: 'stock-levels',
    table: 'stock_levels',
    title: 'Stock on hand',
    singular: 'Stock level',
    listColumns: ['warehouse_id', 'item_id', 'bin_location', 'quantity_on_hand', 'quantity_reserved', 'quantity_on_order', 'average_cost', 'last_counted_on', 'last_movement_at'],
    filterColumns: ['warehouse_id'],
    searchColumns: ['bin_location'],
    defaultSort: { column: 'quantity_on_hand', dir: 'desc' },
  },
  {
    slug: 'stock-movements',
    table: 'stock_movements',
    title: 'Stock movements',
    singular: 'Stock movement',
    listColumns: ['moved_at', 'warehouse_id', 'item_id', 'movement_type', 'quantity', 'unit_cost', 'total_value', 'balance_after', 'work_order_id', 'reference'],
    filterColumns: ['warehouse_id', 'movement_type'],
    searchColumns: ['reference', 'notes'],
    defaultSort: { column: 'moved_at', dir: 'desc' },
  },
  {
    slug: 'warehouses',
    table: 'warehouses',
    title: 'Warehouses',
    singular: 'Warehouse',
    listColumns: ['code', 'name', 'site_id', 'warehouse_type', 'location', 'storekeeper_employee_id', 'active'],
    filterColumns: ['site_id', 'warehouse_type', 'active'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'requisitions',
    table: 'purchase_requisitions',
    title: 'Purchase requisitions',
    singular: 'Requisition',
    listColumns: ['requisition_no', 'title', 'site_id', 'requested_on', 'required_by', 'priority', 'estimated_value', 'status', 'approved_by'],
    filterColumns: ['site_id', 'priority', 'status'],
    searchColumns: ['requisition_no', 'title', 'justification'],
    defaultSort: { column: 'requested_on', dir: 'desc' },
  },
  {
    slug: 'requisition-lines',
    table: 'requisition_lines',
    title: 'Requisition lines',
    singular: 'Requisition line',
    listColumns: ['requisition_id', 'line_no', 'item_id', 'description', 'quantity', 'uom', 'estimated_unit_cost', 'line_total'],
    defaultSort: { column: 'id', dir: 'desc' },
  },
  {
    slug: 'purchase-orders',
    table: 'purchase_orders',
    title: 'Purchase orders',
    singular: 'Purchase order',
    listColumns: ['po_number', 'supplier_id', 'site_id', 'order_date', 'expected_date', 'subtotal', 'tax_amount', 'total_amount', 'received_value', 'status'],
    filterColumns: ['site_id', 'supplier_id', 'status'],
    searchColumns: ['po_number', 'delivery_site', 'incoterms'],
    defaultSort: { column: 'order_date', dir: 'desc' },
  },
  {
    slug: 'purchase-order-lines',
    table: 'purchase_order_lines',
    title: 'Purchase order lines',
    singular: 'PO line',
    listColumns: ['po_id', 'line_no', 'item_id', 'description', 'quantity', 'uom', 'unit_price', 'line_total', 'quantity_received', 'expected_date'],
    defaultSort: { column: 'id', dir: 'desc' },
  },
  {
    slug: 'goods-receipts',
    table: 'goods_receipts',
    title: 'Goods receipts',
    singular: 'Goods receipt',
    listColumns: ['grn_number', 'po_id', 'warehouse_id', 'received_on', 'delivery_note', 'carrier', 'inspection_result', 'total_value'],
    filterColumns: ['warehouse_id', 'inspection_result'],
    searchColumns: ['grn_number', 'delivery_note', 'carrier', 'notes'],
    defaultSort: { column: 'received_on', dir: 'desc' },
  },
  {
    slug: 'goods-receipt-lines',
    table: 'goods_receipt_lines',
    title: 'Goods receipt lines',
    singular: 'GRN line',
    listColumns: ['grn_id', 'item_id', 'quantity_received', 'quantity_accepted', 'quantity_rejected', 'unit_cost', 'line_value', 'batch_no', 'expiry_date', 'rejection_reason'],
    defaultSort: { column: 'id', dir: 'desc' },
  },
  {
    slug: 'suppliers',
    table: 'suppliers',
    title: 'Suppliers',
    singular: 'Supplier',
    listColumns: ['code', 'name', 'category', 'country', 'contact_name', 'payment_terms', 'lead_time_days', 'rating', 'is_local', 'status'],
    filterColumns: ['category', 'status', 'is_local'],
    searchColumns: ['code', 'name', 'contact_name', 'email'],
    defaultSort: { column: 'name', dir: 'asc' },
  },
  {
    slug: 'supplier-invoices',
    table: 'supplier_invoices',
    title: 'Supplier invoices',
    singular: 'Supplier invoice',
    listColumns: ['invoice_no', 'supplier_id', 'po_id', 'invoice_date', 'due_date', 'total_amount', 'paid_amount', 'three_way_matched', 'status', 'paid_on'],
    filterColumns: ['supplier_id', 'status', 'three_way_matched'],
    searchColumns: ['invoice_no'],
    defaultSort: { column: 'invoice_date', dir: 'desc' },
  },

  /* ------------------------------------------------------------ Commercial */
  {
    slug: 'customers',
    table: 'customers',
    title: 'Customers',
    singular: 'Customer',
    listColumns: ['code', 'name', 'customer_type', 'country', 'contact_name', 'credit_limit', 'payment_terms', 'status'],
    filterColumns: ['customer_type', 'status'],
    searchColumns: ['code', 'name', 'contact_name', 'email'],
    defaultSort: { column: 'name', dir: 'asc' },
  },
  {
    slug: 'sales-contracts',
    table: 'sales_contracts',
    title: 'Sales contracts',
    singular: 'Contract',
    listColumns: ['contract_no', 'customer_id', 'commodity', 'contract_type', 'start_date', 'end_date', 'contracted_tonnes', 'delivered_tonnes', 'price_basis', 'base_price', 'incoterms', 'status'],
    filterColumns: ['customer_id', 'commodity', 'contract_type', 'status'],
    searchColumns: ['contract_no', 'title', 'delivery_point'],
    defaultSort: { column: 'start_date', dir: 'desc' },
  },
  {
    slug: 'sales-orders',
    table: 'sales_orders',
    title: 'Sales orders',
    singular: 'Sales order',
    listColumns: ['order_no', 'customer_id', 'contract_id', 'order_date', 'requested_delivery', 'commodity', 'quantity_tonnes', 'unit_price', 'order_value', 'transport_mode', 'status'],
    filterColumns: ['customer_id', 'commodity', 'status', 'transport_mode'],
    searchColumns: ['order_no', 'destination'],
    defaultSort: { column: 'order_date', dir: 'desc' },
  },
  {
    slug: 'shipments',
    table: 'shipments',
    title: 'Shipments',
    singular: 'Shipment',
    listColumns: ['shipment_no', 'customer_id', 'dispatched_on', 'arrived_on', 'transport_mode', 'carrier', 'gross_tonnes', 'dry_tonnes', 'cv_kcal_kg', 'ash_pct', 'invoice_value', 'status'],
    filterColumns: ['site_id', 'customer_id', 'transport_mode', 'status'],
    searchColumns: ['shipment_no', 'carrier', 'vessel_name', 'destination'],
    defaultSort: { column: 'dispatched_on', dir: 'desc' },
  },
  {
    slug: 'weighbridge',
    table: 'weighbridge_tickets',
    title: 'Weighbridge',
    singular: 'Weighbridge ticket',
    listColumns: ['ticket_no', 'weighed_at', 'site_id', 'direction', 'vehicle_rego', 'carrier', 'material', 'gross_kg', 'tare_kg', 'net_kg', 'moisture_pct', 'status'],
    filterColumns: ['site_id', 'direction', 'material', 'status'],
    searchColumns: ['ticket_no', 'vehicle_rego', 'carrier', 'driver_name', 'seal_no'],
    defaultSort: { column: 'weighed_at', dir: 'desc' },
  },
  {
    slug: 'customer-invoices',
    table: 'customer_invoices',
    title: 'Customer invoices',
    singular: 'Customer invoice',
    listColumns: ['invoice_no', 'customer_id', 'shipment_id', 'invoice_date', 'due_date', 'quantity_tonnes', 'subtotal', 'quality_adjustment', 'royalty', 'total_amount', 'received_amount', 'status'],
    filterColumns: ['customer_id', 'status'],
    searchColumns: ['invoice_no'],
    defaultSort: { column: 'invoice_date', dir: 'desc' },
  },
  {
    slug: 'royalties',
    table: 'royalties',
    title: 'Royalties',
    singular: 'Royalty',
    listColumns: ['period_start', 'period_end', 'site_id', 'royalty_type', 'payee', 'basis_tonnes', 'basis_revenue', 'rate_pct', 'amount', 'status', 'paid_on'],
    filterColumns: ['site_id', 'royalty_type', 'status'],
    searchColumns: ['payee', 'reference'],
    defaultSort: { column: 'period_start', dir: 'desc' },
  },
  {
    slug: 'commodity-prices',
    table: 'commodity_prices',
    title: 'Commodity prices',
    singular: 'Price',
    listColumns: ['price_date', 'commodity', 'price', 'currency', 'unit', 'source'],
    filterColumns: ['commodity', 'unit'],
    defaultSort: { column: 'price_date', dir: 'desc' },
  },

  /* --------------------------------------------------------------- Finance */
  {
    slug: 'cost-entries',
    table: 'cost_entries',
    title: 'Cost entries',
    singular: 'Cost entry',
    listColumns: ['entry_date', 'site_id', 'mine_id', 'cost_center_id', 'category', 'cost_type', 'description', 'amount', 'driver_quantity', 'driver_unit'],
    filterColumns: ['site_id', 'mine_id', 'category', 'cost_type', 'cost_center_id'],
    searchColumns: ['description', 'account_code'],
    defaultSort: { column: 'entry_date', dir: 'desc' },
  },
  {
    slug: 'budgets',
    table: 'budgets',
    title: 'Budgets',
    singular: 'Budget',
    listColumns: ['code', 'name', 'site_id', 'fiscal_year', 'version', 'budget_type', 'total_amount', 'currency', 'status', 'approved_by'],
    filterColumns: ['site_id', 'budget_type', 'status', 'fiscal_year'],
    defaultSort: { column: 'fiscal_year', dir: 'desc' },
  },
  {
    slug: 'budget-lines',
    table: 'budget_lines',
    title: 'Budget lines',
    singular: 'Budget line',
    listColumns: ['budget_id', 'cost_center_id', 'account_code', 'description', 'period_month', 'amount', 'quantity', 'unit'],
    filterColumns: ['budget_id', 'cost_center_id'],
    defaultSort: { column: 'id', dir: 'asc' },
  },
  {
    slug: 'cost-centers',
    table: 'cost_centers',
    title: 'Cost centres',
    singular: 'Cost centre',
    listColumns: ['code', 'name', 'site_id', 'category', 'parent_id', 'active'],
    filterColumns: ['site_id', 'category', 'active'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'kpi-definitions',
    table: 'kpi_definitions',
    title: 'KPI definitions',
    singular: 'KPI',
    listColumns: ['code', 'name', 'module', 'unit', 'direction', 'frequency', 'formula', 'active'],
    filterColumns: ['module', 'direction', 'frequency', 'active'],
    searchColumns: ['code', 'name', 'formula'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'kpi-values',
    table: 'kpi_values',
    title: 'KPI results',
    singular: 'KPI result',
    listColumns: ['period_start', 'period_end', 'kpi_id', 'site_id', 'target_value', 'actual_value', 'variance_pct', 'status', 'commentary'],
    filterColumns: ['kpi_id', 'site_id', 'status'],
    defaultSort: { column: 'period_start', dir: 'desc' },
  },

  /* ------------------------------------------------------------ Compliance */
  {
    slug: 'tenements',
    table: 'tenements',
    title: 'Tenements and licences',
    singular: 'Tenement',
    listColumns: ['tenement_no', 'name', 'site_id', 'tenement_type', 'granted_on', 'expires_on', 'area_km2', 'annual_rent', 'expenditure_commitment', 'expenditure_to_date', 'status'],
    filterColumns: ['site_id', 'tenement_type', 'status'],
    searchColumns: ['tenement_no', 'name', 'holder', 'jurisdiction'],
    defaultSort: { column: 'expires_on', dir: 'asc' },
  },
  {
    slug: 'obligations',
    table: 'regulatory_obligations',
    title: 'Regulatory obligations',
    singular: 'Obligation',
    listColumns: ['reference', 'title', 'site_id', 'obligation_type', 'regulator', 'frequency', 'next_due_on', 'responsible', 'penalty_risk', 'status'],
    filterColumns: ['site_id', 'obligation_type', 'status', 'penalty_risk'],
    searchColumns: ['reference', 'title', 'regulator', 'legislation'],
    defaultSort: { column: 'next_due_on', dir: 'asc' },
  },
  {
    slug: 'audits',
    table: 'audits',
    title: 'Audits',
    singular: 'Audit',
    listColumns: ['audit_no', 'title', 'site_id', 'audit_type', 'standard', 'auditor', 'planned_on', 'performed_on', 'findings_count', 'major_findings', 'score_pct', 'result', 'status'],
    filterColumns: ['site_id', 'audit_type', 'status', 'result'],
    searchColumns: ['audit_no', 'title', 'auditor', 'standard'],
    defaultSort: { column: 'planned_on', dir: 'desc' },
  },
  {
    slug: 'audit-findings',
    table: 'audit_findings',
    title: 'Audit findings',
    singular: 'Finding',
    listColumns: ['finding_no', 'audit_id', 'clause', 'severity', 'description', 'responsible', 'due_on', 'closed_on', 'status'],
    filterColumns: ['audit_id', 'severity', 'status'],
    searchColumns: ['finding_no', 'description', 'clause', 'responsible'],
    defaultSort: { column: 'due_on', dir: 'asc' },
  },
  {
    slug: 'documents',
    table: 'documents',
    title: 'Document control',
    singular: 'Document',
    listColumns: ['doc_number', 'title', 'site_id', 'doc_type', 'discipline', 'version', 'owner', 'effective_on', 'review_due_on', 'status'],
    filterColumns: ['site_id', 'doc_type', 'status'],
    searchColumns: ['doc_number', 'title', 'owner', 'discipline'],
    defaultSort: { column: 'review_due_on', dir: 'asc' },
  },

  /* ------------------------------------------------------------ Foundation */
  {
    slug: 'sites',
    table: 'sites',
    title: 'Sites',
    singular: 'Site',
    listColumns: ['code', 'name', 'country', 'region', 'latitude', 'longitude', 'elevation_m', 'workforce_target', 'commissioned_on', 'status'],
    filterColumns: ['status', 'country'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'mines',
    table: 'mines',
    title: 'Mines',
    singular: 'Mine',
    listColumns: ['code', 'name', 'site_id', 'commodity', 'mine_type', 'depth_m', 'area_hectares', 'life_of_mine_years', 'opened_on', 'status'],
    filterColumns: ['site_id', 'commodity', 'mine_type', 'status'],
    searchColumns: ['code', 'name', 'description'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'mining-areas',
    table: 'mining_areas',
    title: 'Mining areas',
    singular: 'Mining area',
    listColumns: ['code', 'name', 'mine_id', 'area_type', 'seam_name', 'rl_from_m', 'rl_to_m', 'strike_length_m', 'status'],
    filterColumns: ['mine_id', 'area_type', 'status'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'departments',
    table: 'departments',
    title: 'Departments',
    singular: 'Department',
    listColumns: ['code', 'name', 'site_id', 'discipline'],
    filterColumns: ['site_id', 'discipline'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'users',
    table: 'app_users',
    title: 'Users',
    singular: 'User',
    listColumns: ['email', 'full_name', 'job_title', 'site_id', 'status', 'last_login_at', 'created_at'],
    filterColumns: ['site_id', 'status'],
    searchColumns: ['email', 'full_name', 'job_title'],
    defaultSort: { column: 'full_name', dir: 'asc' },
  },
  {
    slug: 'roles',
    table: 'roles',
    title: 'Roles',
    singular: 'Role',
    listColumns: ['code', 'name', 'description', 'is_system', 'created_at'],
    filterColumns: ['is_system'],
    defaultSort: { column: 'code', dir: 'asc' },
  },
  {
    slug: 'role-permissions',
    table: 'role_permissions',
    title: 'Role permissions',
    singular: 'Permission',
    listColumns: ['role_id', 'permission'],
    filterColumns: ['role_id'],
    searchColumns: ['permission'],
    defaultSort: { column: 'id', dir: 'asc' },
  },
  {
    slug: 'audit-log',
    table: 'audit_log',
    title: 'Audit log',
    singular: 'Audit entry',
    description: 'Every change made through the platform, with the actor and a summary.',
    listColumns: ['at', 'entity', 'entity_id', 'action', 'actor', 'summary'],
    filterColumns: ['entity', 'action'],
    searchColumns: ['entity', 'actor', 'summary'],
    defaultSort: { column: 'at', dir: 'desc' },
    readOnly: true,
  },
]

export const ENTITIES: EntityConfig[] = defs

export const ENTITY_BY_SLUG = new Map(defs.map((d) => [d.slug, d]))
