import {
  Activity, AlertTriangle, Anvil, Award, Banknote, BarChart3, Bell, Blocks, BookOpen, Boxes,
  Briefcase, Building2, Calendar, ClipboardCheck, ClipboardList, Cog, Coins, Container, Cpu,
  Database, Droplets, FileText, FlaskConical, Flame, Fuel, Gauge, GraduationCap, HardHat,
  Hammer, Heart, Layers, Leaf, LifeBuoy, Lock, Map, Mountain, Package, PackageSearch, PieChart,
  Radar, Recycle, Scale, ScrollText, Settings, Share2, Shield, ShieldAlert, ShoppingCart,
  Siren, SlidersHorizontal, Sparkles, Stethoscope, Target, Thermometer, Timer, Truck, Users,
  Wallet, Warehouse, Wind, Wrench, Zap, type LucideIcon,
} from 'lucide-react'

export interface NavItem {
  label: string
  to: string
  icon: LucideIcon
  /** Extra terms the command palette should match on. */
  keywords?: string
  badge?: 'alerts'
}

export interface NavGroup {
  id: string
  label: string
  icon: LucideIcon
  items: NavItem[]
}

/** Entity screens live under /m/<slug>; dashboards get their own paths. */
export const NAV: NavGroup[] = [
  {
    id: 'overview',
    label: 'Overview',
    icon: Gauge,
    items: [
      { label: 'Group dashboard', to: '/', icon: Gauge, keywords: 'home executive summary kpi' },
      { label: 'Site scorecard', to: '/scorecard', icon: Target, keywords: 'kpi performance sites comparison' },
      { label: 'Alerts', to: '/alerts', icon: Bell, keywords: 'notifications warnings exceptions', badge: 'alerts' },
    ],
  },
  {
    id: 'operations',
    label: 'Mining operations',
    icon: Mountain,
    items: [
      { label: 'Production', to: '/operations', icon: BarChart3, keywords: 'tonnes ore waste strip ratio dashboard' },
      { label: 'Production records', to: '/m/production-records', icon: ClipboardList, keywords: 'shift tonnes capture' },
      { label: 'Mine plans', to: '/m/mine-plans', icon: Map, keywords: 'budget plan attainment' },
      { label: 'Shifts', to: '/m/shifts', icon: Timer, keywords: 'roster crew handover' },
      { label: 'Shift log book', to: '/m/shift-logs', icon: ScrollText, keywords: 'statutory handover entries' },
      { label: 'Development', to: '/m/development', icon: Layers, keywords: 'underground advance metres heading' },
      { label: 'Drill patterns', to: '/m/drill-patterns', icon: Blocks, keywords: 'burden spacing blast design' },
      { label: 'Production drilling', to: '/m/drilling', icon: Anvil, keywords: 'metres rig penetration' },
      { label: 'Blast register', to: '/m/blasts', icon: Flame, keywords: 'explosives ppv misfire vibration' },
      { label: 'Explosives magazines', to: '/m/explosives-magazines', icon: Lock, keywords: 'magazine licence anfo' },
      { label: 'Explosives movements', to: '/m/explosives-transactions', icon: Share2, keywords: 'issue receipt balance' },
      { label: 'Haulage cycles', to: '/m/haulage', icon: Truck, keywords: 'truck payload cycle time queue' },
      { label: 'Stockpiles', to: '/m/stockpiles', icon: Boxes, keywords: 'rom product balance' },
      { label: 'Stockpile movements', to: '/m/stockpile-movements', icon: Container, keywords: 'reclaim rehandle' },
      { label: 'Ventilation', to: '/m/ventilation', icon: Wind, keywords: 'airflow underground quantity' },
      { label: 'Gas monitoring', to: '/m/gas-readings', icon: Siren, keywords: 'methane ch4 carbon monoxide alarm' },
      { label: 'Ground support', to: '/m/ground-support', icon: Shield, keywords: 'bolts mesh shotcrete' },
      { label: 'Dewatering', to: '/m/dewatering', icon: Droplets, keywords: 'pumping water level' },
    ],
  },
  {
    id: 'geology',
    label: 'Geology and resources',
    icon: FlaskConical,
    items: [
      { label: 'Geology dashboard', to: '/geology', icon: PieChart, keywords: 'resource reserve grade drilling' },
      { label: 'Exploration projects', to: '/m/exploration-projects', icon: Radar, keywords: 'greenfield brownfield budget' },
      { label: 'Drill programmes', to: '/m/drill-programs', icon: ClipboardList, keywords: 'diamond rc metres' },
      { label: 'Drillholes', to: '/m/drillholes', icon: Anvil, keywords: 'collar survey depth' },
      { label: 'Geological logging', to: '/m/lithology', icon: Layers, keywords: 'lithology alteration rqd' },
      { label: 'Samples', to: '/m/samples', icon: FlaskConical, keywords: 'core qaqc duplicate' },
      { label: 'Laboratory batches', to: '/m/sample-batches', icon: Package, keywords: 'lab turnaround dispatch' },
      { label: 'Assay results', to: '/m/assays', icon: Sparkles, keywords: 'gold copper element grade' },
      { label: 'Coal quality', to: '/m/coal-quality', icon: Flame, keywords: 'ash volatile calorific sulphur' },
      { label: 'Block model', to: '/m/resource-blocks', icon: Blocks, keywords: 'grade control tonnes classification' },
      { label: 'Resources and reserves', to: '/m/resource-statements', icon: Scale, keywords: 'jorc measured indicated inferred' },
      { label: 'Geotechnical', to: '/m/geotechnical', icon: Activity, keywords: 'slope radar displacement prism' },
      { label: 'Survey pickups', to: '/m/survey-pickups', icon: Map, keywords: 'reconciliation volume drone' },
    ],
  },
  {
    id: 'processing',
    label: 'Processing',
    icon: Cpu,
    items: [
      { label: 'Plant dashboard', to: '/processing', icon: Gauge, keywords: 'throughput recovery yield' },
      { label: 'Plants', to: '/m/plants', icon: Cpu, keywords: 'cil chpp concentrator' },
      { label: 'Circuits', to: '/m/plant-circuits', icon: Share2, keywords: 'milling leach flotation' },
      { label: 'Plant runs', to: '/m/plant-runs', icon: BarChart3, keywords: 'daily metallurgical balance feed' },
      { label: 'Reagents', to: '/m/reagents', icon: FlaskConical, keywords: 'cyanide lime dosage consumption' },
      { label: 'Metallurgical samples', to: '/m/met-samples', icon: FlaskConical, keywords: 'stream p80 solids' },
      { label: 'Gold pours', to: '/m/gold-pours', icon: Coins, keywords: 'dore bullion fineness gold room' },
      { label: 'Bullion shipments', to: '/m/bullion-shipments', icon: Truck, keywords: 'refinery settlement variance' },
      { label: 'Product specs', to: '/m/product-specs', icon: ClipboardCheck, keywords: 'rb1 rb3 concentrate specification' },
      { label: 'Product quality', to: '/m/quality-samples', icon: Award, keywords: 'cv ash moisture within spec' },
      { label: 'Tailings facilities', to: '/m/tailings-facilities', icon: Droplets, keywords: 'tsf dam gistm freeboard' },
      { label: 'Tailings monitoring', to: '/m/tailings-readings', icon: Activity, keywords: 'phreatic seepage pond level' },
    ],
  },
  {
    id: 'maintenance',
    label: 'Assets and maintenance',
    icon: Wrench,
    items: [
      { label: 'Fleet dashboard', to: '/maintenance', icon: Gauge, keywords: 'availability utilisation mtbf' },
      { label: 'Asset register', to: '/m/assets', icon: Truck, keywords: 'equipment fleet fixed plant' },
      { label: 'Work orders', to: '/m/work-orders', icon: Wrench, keywords: 'breakdown preventive corrective' },
      { label: 'Work order tasks', to: '/m/work-order-tasks', icon: ClipboardList, keywords: 'labour trade steps' },
      { label: 'Work order parts', to: '/m/work-order-parts', icon: Package, keywords: 'spares issued' },
      { label: 'Maintenance plans', to: '/m/maintenance-plans', icon: Calendar, keywords: 'pm service interval strategy' },
      { label: 'Downtime', to: '/m/downtime', icon: Timer, keywords: 'availability loss delay breakdown' },
      { label: 'Meter readings', to: '/m/meter-readings', icon: Gauge, keywords: 'hours kilometres telemetry' },
      { label: 'Fuel and lubricants', to: '/m/fuel', icon: Fuel, keywords: 'diesel litres bowser burn rate' },
      { label: 'Tyre management', to: '/m/tyres', icon: Cog, keywords: 'otr tread retread' },
      { label: 'Equipment inspections', to: '/m/equipment-inspections', icon: ClipboardCheck, keywords: 'pre start defect' },
      { label: 'Failure codes', to: '/m/failure-codes', icon: AlertTriangle, keywords: 'taxonomy system severity' },
      { label: 'Asset categories', to: '/m/asset-categories', icon: Blocks, keywords: 'class meter type' },
    ],
  },
  {
    id: 'workforce',
    label: 'Workforce',
    icon: Users,
    items: [
      { label: 'Workforce dashboard', to: '/workforce', icon: Gauge, keywords: 'headcount attendance absenteeism' },
      { label: 'Employees', to: '/m/employees', icon: Users, keywords: 'people staff register' },
      { label: 'Tag board', to: '/m/tag-board', icon: HardHat, keywords: 'underground lamp room who is in' },
      { label: 'Crews', to: '/m/crews', icon: Users, keywords: 'team supervisor shift' },
      { label: 'Crew membership', to: '/m/crew-members', icon: Users, keywords: 'assignment roster' },
      { label: 'Shift patterns', to: '/m/shift-patterns', icon: Timer, keywords: 'roster rotation fifo' },
      { label: 'Attendance', to: '/m/attendance', icon: ClipboardCheck, keywords: 'clock in absence fitness' },
      { label: 'Competency types', to: '/m/competencies', icon: Award, keywords: 'licence ticket statutory' },
      { label: 'Competency records', to: '/m/employee-competencies', icon: Award, keywords: 'expiry certificate valid' },
      { label: 'Training catalogue', to: '/m/training-courses', icon: GraduationCap, keywords: 'course provider' },
      { label: 'Training records', to: '/m/training-records', icon: GraduationCap, keywords: 'completed pass score' },
      { label: 'Leave', to: '/m/leave', icon: Calendar, keywords: 'annual sick absence' },
      { label: 'Occupational health', to: '/m/medicals', icon: Stethoscope, keywords: 'medical audiometric spirometry fitness' },
      { label: 'Payroll periods', to: '/m/payroll-periods', icon: Wallet, keywords: 'pay run gross net' },
      { label: 'Payroll detail', to: '/m/payroll-lines', icon: Banknote, keywords: 'earnings deductions allowance' },
      { label: 'Employee relations', to: '/m/er-cases', icon: Briefcase, keywords: 'grievance disciplinary union' },
      { label: 'Contractors', to: '/m/contractors', icon: Building2, keywords: 'vendor scope prequalified' },
    ],
  },
  {
    id: 'safety',
    label: 'Health and safety',
    icon: ShieldAlert,
    items: [
      { label: 'Safety dashboard', to: '/safety', icon: Gauge, keywords: 'trifr ltifr incidents' },
      { label: 'Incidents', to: '/m/incidents', icon: Siren, keywords: 'injury near miss lti investigation' },
      { label: 'Corrective actions', to: '/m/actions', icon: ClipboardCheck, keywords: 'capa overdue close out' },
      { label: 'Hazard register', to: '/m/hazards', icon: AlertTriangle, keywords: 'principal risk control' },
      { label: 'Risk assessments', to: '/m/risk-assessments', icon: ClipboardList, keywords: 'jsa take 5 bowtie hazop' },
      { label: 'Observations', to: '/m/observations', icon: Radar, keywords: 'behavioural unsafe act condition' },
      { label: 'Permits to work', to: '/m/permits', icon: Lock, keywords: 'hot work confined space isolation' },
      { label: 'HSE inspections', to: '/m/hse-inspections', icon: ClipboardCheck, keywords: 'statutory workplace fire' },
      { label: 'Toolbox talks', to: '/m/toolbox-talks', icon: Users, keywords: 'pre shift meeting topic' },
      { label: 'PPE issues', to: '/m/ppe', icon: HardHat, keywords: 'boots respirator self rescuer' },
      { label: 'Emergency drills', to: '/m/emergency-drills', icon: LifeBuoy, keywords: 'evacuation rescue muster' },
    ],
  },
  {
    id: 'environment',
    label: 'Environment and community',
    icon: Leaf,
    items: [
      { label: 'Environment dashboard', to: '/environment', icon: Gauge, keywords: 'compliance water emissions' },
      { label: 'Monitoring results', to: '/m/environmental-monitoring', icon: Thermometer, keywords: 'water air dust noise limit' },
      { label: 'Water balance', to: '/m/water-balance', icon: Droplets, keywords: 'abstraction recycled discharge' },
      { label: 'Energy and emissions', to: '/m/energy', icon: Zap, keywords: 'power kwh co2e scope' },
      { label: 'Waste management', to: '/m/waste', icon: Recycle, keywords: 'hazardous scrap oil manifest' },
      { label: 'Rehabilitation', to: '/m/rehabilitation', icon: Leaf, keywords: 'closure revegetation provision' },
      { label: 'Community relations', to: '/m/community', icon: Users, keywords: 'grievance stakeholder donation' },
    ],
  },
  {
    id: 'supply',
    label: 'Supply chain',
    icon: Warehouse,
    items: [
      { label: 'Supply dashboard', to: '/supply', icon: Gauge, keywords: 'stock value reorder spend' },
      { label: 'Item catalogue', to: '/m/items', icon: PackageSearch, keywords: 'spares consumables part' },
      { label: 'Stock on hand', to: '/m/stock-levels', icon: Boxes, keywords: 'inventory bin quantity' },
      { label: 'Stock movements', to: '/m/stock-movements', icon: Share2, keywords: 'issue receipt adjustment' },
      { label: 'Warehouses', to: '/m/warehouses', icon: Warehouse, keywords: 'store fuel farm' },
      { label: 'Requisitions', to: '/m/requisitions', icon: ClipboardList, keywords: 'pr approval request' },
      { label: 'Requisition lines', to: '/m/requisition-lines', icon: ClipboardList, keywords: 'pr detail' },
      { label: 'Purchase orders', to: '/m/purchase-orders', icon: ShoppingCart, keywords: 'po supplier commitment' },
      { label: 'Purchase order lines', to: '/m/purchase-order-lines', icon: ShoppingCart, keywords: 'po detail' },
      { label: 'Goods receipts', to: '/m/goods-receipts', icon: Package, keywords: 'grn delivery inspection' },
      { label: 'Goods receipt lines', to: '/m/goods-receipt-lines', icon: Package, keywords: 'grn detail rejected' },
      { label: 'Suppliers', to: '/m/suppliers', icon: Building2, keywords: 'vendor rating terms' },
      { label: 'Supplier invoices', to: '/m/supplier-invoices', icon: FileText, keywords: 'accounts payable three way match' },
    ],
  },
  {
    id: 'commercial',
    label: 'Sales and logistics',
    icon: Coins,
    items: [
      { label: 'Sales dashboard', to: '/commercial', icon: Gauge, keywords: 'revenue tonnes despatched' },
      { label: 'Customers', to: '/m/customers', icon: Building2, keywords: 'offtaker refinery utility' },
      { label: 'Sales contracts', to: '/m/sales-contracts', icon: FileText, keywords: 'offtake index price' },
      { label: 'Sales orders', to: '/m/sales-orders', icon: ShoppingCart, keywords: 'order tonnage destination' },
      { label: 'Shipments', to: '/m/shipments', icon: Truck, keywords: 'rail vessel despatch quality' },
      { label: 'Weighbridge', to: '/m/weighbridge', icon: Scale, keywords: 'ticket gross tare net vehicle' },
      { label: 'Customer invoices', to: '/m/customer-invoices', icon: Banknote, keywords: 'receivable provisional final' },
      { label: 'Royalties', to: '/m/royalties', icon: Scale, keywords: 'government landowner community' },
      { label: 'Commodity prices', to: '/m/commodity-prices', icon: BarChart3, keywords: 'gold copper coal index' },
    ],
  },
  {
    id: 'finance',
    label: 'Cost and performance',
    icon: Wallet,
    items: [
      { label: 'Cost dashboard', to: '/finance', icon: Gauge, keywords: 'cost per tonne budget variance' },
      { label: 'Cost entries', to: '/m/cost-entries', icon: Banknote, keywords: 'actuals posting category' },
      { label: 'Budgets', to: '/m/budgets', icon: Wallet, keywords: 'operating capital fiscal year' },
      { label: 'Budget lines', to: '/m/budget-lines', icon: ClipboardList, keywords: 'phasing month allocation' },
      { label: 'Cost centres', to: '/m/cost-centers', icon: Blocks, keywords: 'coding structure' },
      { label: 'KPI definitions', to: '/m/kpi-definitions', icon: Target, keywords: 'metric formula frequency' },
      { label: 'KPI results', to: '/m/kpi-values', icon: BarChart3, keywords: 'target actual variance' },
    ],
  },
  {
    id: 'compliance',
    label: 'Compliance and governance',
    icon: ClipboardCheck,
    items: [
      { label: 'Compliance calendar', to: '/compliance', icon: Calendar, keywords: 'due dates obligations expiry' },
      { label: 'Tenements and licences', to: '/m/tenements', icon: Map, keywords: 'lease right expenditure' },
      { label: 'Regulatory obligations', to: '/m/obligations', icon: ScrollText, keywords: 'report payment regulator' },
      { label: 'Audits', to: '/m/audits', icon: ClipboardCheck, keywords: 'iso internal external' },
      { label: 'Audit findings', to: '/m/audit-findings', icon: AlertTriangle, keywords: 'non conformance clause' },
      { label: 'Document control', to: '/m/documents', icon: BookOpen, keywords: 'procedure policy review due' },
    ],
  },
  {
    id: 'admin',
    label: 'Configuration',
    icon: Settings,
    items: [
      { label: 'Sites', to: '/m/sites', icon: Building2, keywords: 'operation location' },
      { label: 'Mines', to: '/m/mines', icon: Mountain, keywords: 'pit underground commodity' },
      { label: 'Mining areas', to: '/m/mining-areas', icon: Layers, keywords: 'bench level panel seam' },
      { label: 'Departments', to: '/m/departments', icon: Briefcase, keywords: 'discipline structure' },
      { label: 'Users', to: '/m/users', icon: Users, keywords: 'accounts access' },
      { label: 'Roles', to: '/m/roles', icon: Shield, keywords: 'permission group' },
      { label: 'Role permissions', to: '/m/role-permissions', icon: Lock, keywords: 'grant module action' },
      { label: 'Audit log', to: '/m/audit-log', icon: Database, keywords: 'changes history who did what' },
      { label: 'Data and schema', to: '/admin/data', icon: SlidersHorizontal, keywords: 'tables reset export sql' },
      { label: 'SQL console', to: '/admin/sql', icon: Hammer, keywords: 'query run postgres' },
      { label: 'About this platform', to: '/admin/about', icon: Heart, keywords: 'help documentation supabase' },
    ],
  },
]

export const ALL_NAV_ITEMS: (NavItem & { group: string })[] = NAV.flatMap((g) =>
  g.items.map((item) => ({ ...item, group: g.label })),
)
